version: "2"
services:
  limesurvey:
    image: zburditt480/limesurvey
    container_name: "limesurvey-${DEPLOY}"
    volumes:
      - "/var/log/docker/limesurvey-${DEPLOY}:/var/log/apache2"
    environment:
      - "TZ=America/Chicago"
    networks:
      - webtools
  db:
    image: mariadb:latest
    container_name: "lime_db-${DEPLOY}"
    volumes:
      - "./db-conf:/etc/mysql"
      - "./data:/var/lib/mysql"
      - "./my.cnf:/root/.my.cnf"
    environment:
      - "MYSQL_ROOT_PASSWORD=${ROOT_PWD}"
      - "TZ=America/Chicago"
    networks:
      - webtools
networks:
  webtools:
    external:
      name: "${NETWORK}-${DEPLOY}"
